name: 08 - Using Variables

on: 
  push: 
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "I will be overwritten"
  UNDEFINED_VARIABLE: ${{ vars.UNDEFINED_VARIABLE || 'default_value' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env var"
      OVERWRITTEN: "I have been overwritten at the job level"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am a step env var"
          step_var2: "I am another step var"
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten: $OVERWRITTEN"
      - name: Overwrite Job Variable
        env:
          OVERWRITTEN: "I have been overwritten at the step level"
        run: |
          echo "Step env var: $OVERWRITTEN"
  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Multiple workflows variables
        run: |
          echo "Org var: ${{ vars.ORG_VAR }}"
          echo "Org overwritten var: ${{ vars.OVERWRITTEN_VAR }}"
          echo "Repository var: ${{ vars.REPOSITORY_VAR }}"
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print prod variables
        run: |
          echo "Org var: ${{ vars.ORG_VAR }}"
          echo "Org overwritten var: ${{ vars.OVERWRITTEN_VAR }}"
          echo "Repository var: ${{ vars.REPOSITORY_VAR }}"
          echo "Environment overwritten var: ${{ vars.OVERWRITTEN_VAR }}"
  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print undefined variable
        run: |
          echo "Undefined variable: $UNDEFINED_VARIABLE"