name: 16 - Working with Environments
on: 
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Deploy to staging
        run: |
          echo "deploying to staging"
  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Running E2e tests
        run: echo "Running e2e tests"
  deploy-prod:
    runs-on: ubuntu-latest
    needs: e2e-tests
    environment: prod
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Deploy to prod
        run: |
          echo "deploying to prod"
